# Generated by Django 6.0.3 on 2026-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.svgrepo.com/show/66980/fast-food-placeholder.svg', max_length=500),
        ),
    ]
