# Generated by Django 6.0.3 on 2026-03-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_name',
            new_name='user',
        ),
    ]
