# Generated by Django 6.0.3 on 2026-03-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_name_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='user_name',
        ),
    ]
